---

- hosts: all
  become: true
  pre_tasks:

  
  - name: install updates (CentOS)
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "Centos"



  - name: Install epel-release and dnf
    dnf:
      name:
        - epel-release
        - dnf
    when: ansible_distribution == "CentOS"

  - name: Update CentOS Server
    dnf:
      update_cache: yes
      name: "*"
      state: latest
    when: ansible_distribution == "CentOS"


- hosts: centos
  become: true
  roles:
    - centos

- hosts: ubuntu
  become: true
  roles:
    - ubuntu
    
- name: install nagios on CentOS     
  hosts: nagios_CentOS
  become: true
  roles:
    - nagios_CentOS

