---

  - name: Install necessary prerequisites
    apt:
      name:
        - default-jre
        - apt-transport-https
        - curl
        - software-properties-common
      state: present
    become: yes

  - name: Add Elasticsearch APT repository GPG key
    apt_key:
      url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    become: yes

  - name: Add the Elasticsearch APT repository
    apt_repository:
      repo: "deb https://artifacts.elastic.co/packages/7.x/apt stable main"
      state: present
    become: yes

  - name: Install Elasticsearch
    apt:
      name: elasticsearch
      state: present
    become: yes

  - name: Enable and start Elasticsearch service
    systemd:
      name: elasticsearch
      enabled: yes
      state: started
    become: yes

  - name: Install Kibana
    apt:
      name: kibana
      state: present
    become: yes

  - name: Enable and start Kibana service
    systemd:
      name: kibana
      enabled: yes
      state: started
    become: yes

  - name: Install Logstash
    apt:
      name: logstash
      state: present
    become: yes

  - name: Enable and start Logstash service
    systemd:
      name: logstash
      enabled: yes
      state: started
    become: yes

  - name: Restart Elasticsearch and Kibana services
    systemd:
      name: "{{ item }}"
      state: restarted
    loop:
      - elasticsearch
      - kibana

  - name: Create directory
    tags: dir
    file:
      path: ~/prometheus
      state: directory

  - name: Download Prometheus
    unarchive:
      src: https://github.com/prometheus/prometheus/releases/download/v2.39.1/prometheus-2.39.1.linux-amd64.tar.gz
      dest: ~/prometheus
      remote_src: yes
      mode: 0777
      owner: root
      group: root

  - name: Add executables of Prometheus in a path
    tags: exe
    shell: |
      cd ~/prometheus/prometheus*
      sudo rsync -av . /usr/local/bin/prometheus/

  - name: Copy Prometheus file
    tags: file
    copy:
      src: prometheus.service
      dest: /etc/systemd/system/
      owner: root
      group: root
      mode: 777

  - name: Start HTTPD
    tags: httpd
    service:
      name: prometheus
      state: restarted
      enabled: true

  - name: Install Apache
    apt:
      name: apache2
      state: present

  - name: Start Apache service
    systemd:
      name: apache2
      state: started
      enabled: yes

  - name: Install MariaDB
    apt:
      name: mariadb-server
      state: present

  - name: Start MariaDB service
    systemd:
       name: mariadb
       state: started
       enabled: yes

  - name: Install PHP
    apt:
      name: php
      state: present

  - name: Restart Apache service
    systemd:
      name: apache2
      state: restarted
      
  - name: Downloading Grafana package
    get_url:
      url: https://dl.grafana.com/enterprise/release/grafana-enterprise-7.5.7-1.x86_64.rpm
      dest: /tmp/grafana-enterprise-7.5.7-1.x86_64.rpm

  - name: Installing InfluxDB
    apt:
      name:
        - influxdb
      state: latest

  - name: Making sure that InfluxDB is enabled and started
    service:
      name: influxdb
      state: started
      enabled: true

  - name: Adding Grafana repository key
    shell: |
      sudo wget -q -O /usr/share/keyrings/grafana.key https://packages.grafana.com/gpg.key

  - name: Adding Grafana repository
    apt_repository:
      repo: deb [signed-by=/usr/share/keyrings/grafana.key] https://packages.grafana.com/oss/deb stable main
      state: present

  - name: Updating repositories
    apt:
      update_cache: yes

  - name: Installing Grafana
    apt:
      name:
        - grafana
      state: latest

  - name: Making sure that Grafana server is started and enabled
    service:
      name: grafana-server
      state: restarted
      enabled: true

