---

- name: Update package cache (CentOS)
  tags: always
  dnf:
    update_cachce: yes
  when: "ansible_os_family == 'CentOS'"

  
- name: install required packages
  package:
    name: "{{ item }}"
    state: present
  loop:
    - apache2
    - libapache2-mod-php
    - php-gd
    - libgd-dev
    - unzip
  when: "ansible_os_family == 'Redhat'"
